---
title: "Grand Valley Magazine Project"
author: "Matthew Dickinson & Foster Thorburn"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(readr)
library(flextable)
```

```{r data import}
data_import <- read_csv("STA 419 GV Magazine Survey.csv")

data_dict <- read_csv("Data Dictionary for GVM survey - Final.csv")
```

```{r renaming columns}
gvm_main <- data_import |>
  select(12:62) |>
  slice(c(-1,-2))

colnames(gvm_main) <- data_dict$variable_name
```

### Cleaning to do
* columns (likert) to numeric
* where_read to categorize
* num issues: 1,2,6,7 (0, 1, 2, 3)
* gvsu_engagment to category
* age to be actual categorize
* num_articles change 'NOT_APPLICABLE' to "more than 10"
* drive to website category
* website_only to yes/no
* website_engagment to category


```{r matthew cleaning columns}
gvm_clean <- gvm_main |>
  select(-1, -51) |>
  mutate(
    where_read = case_when(
      where_read == "1" ~ "GVM Website",
      where_read == "2" ~ "Print issues",
      where_read == "3" ~ "Both",
      TRUE ~ "I don't read the GVM"),
    num_issues = as.numeric(case_when(
      num_issues == "1" ~ 0,
      num_issues == "2" ~ 2,
      num_issues == "6" ~ 3,
      TRUE ~ 1)),
    gvsu_engagement = case_when(
      gvsu_engagement == "1" ~ "Disagree",
      gvsu_engagement == "2" ~ "Neutral",
      TRUE ~ "Agree"),
    age = case_when(
      age == "1" ~ "17-24",
      age == "2" ~ "25-35",
      age == "3" ~ "36-49",
      age == "4" ~ "50-65",
      TRUE ~ "66+"
    ))


```

```{r foster cleaning}
gvm_clean <- gvm_clean %>% mutate(num_articles=recode(num_articles,
                                'NOT_APPLICABLE' = '10+'))
gvm_clean <- gvm_clean %>% mutate(website_only=recode(website_only,
                                '1' = 'Yes',
                                '2' = "I don't know/I'm not sure", 
                                '3' = "No"))

gvm_clean <- gvm_clean %>% mutate(website_engagment=recode(website_engagment,
                                '1' = 'Larger variety of content', 
                                '2' = 'Easier navigation',
                                '3' = 'It is currently engaging',
                                '8' = 'More specific recommendations',
                                '4' = "I don't know/I'm not sure",
                                '5' = "I don't use the website", 
                                '7' = 'Other'))

gvm_clean <- gvm_clean %>% mutate(drive_to_website=recode(drive_to_website,
                                '1' = 'Word of Mouth', 
                                '2' = 'Email',
                                '3' = 'Social Media',
                                '4' = 'Link within printed Issue'))
                                 
gvm_clean <- type.convert(gvm_clean, as.is = TRUE)
```

```{r frequency for relation}
# vector for column names
relation_cols <- gvm_clean |> select(starts_with("relation")) |> colnames()

# empty vector to store counts
relation_counts <- vector()

# finding counts for each column name
for (i in 1:length(relation_cols)){
  # print(gvm_clean[relation_cols[i]])
  relation_counts[i] = length(which(gvm_clean[relation_cols[i]] == 1))
}

# storing information in df
relation_df <- data.frame(
  relation_cols,
  relation_counts
)

# cleaning names
relation_df <- relation_df |> mutate(relation_cols = str_replace_all(relation_cols, "relation_", ""))
```

```{r}
#Most Info df
counts <-c(
length(which(gvm_clean$most_info_gv_emails == 1)),
length(which(gvm_clean$most_info_gvm_print == 1)),
length(which(gvm_clean$most_info_gvm_website == 1)),
length(which(gvm_clean$most_info_gv_publications == 1)),
length(which(gvm_clean$most_info_media == 1)),
length(which(gvm_clean$most_info_wordofmouth_alumni == 1)),
length(which(gvm_clean$most_info_lanthorn == 1)),
length(which(gvm_clean$most_info_socialmedia == 1)),
length(which(gvm_clean$most_info_other == 1))
)

most_info_df <- data.frame(
  answer = c("Emails from GVSU","Grand Valley Magazine Print Issues","Grand Valley Magazine Website","Other GVSU Publications","Local or National Media","Word of Mouth/Other Alumni","The Lanthorn","Social Media","Other"),
  count = counts
)
```


```{r frequency for action}
# vector for column names
action_cols <- gvm_clean |> select(starts_with("action")) |> colnames()

# empty vector to store counts
action_counts <- vector()

# finding counts for each column name
for (i in 1:length(action_cols)){
  # print(gvm_clean[relation_cols[i]])
  action_counts[i] = length(which(gvm_clean[action_cols[i]] == 1))
}


# storing information in df
action_df <- data.frame(
  action_cols,
  action_counts
)

# cleaning names
action_df <- action_df |> mutate(action_cols = str_replace_all(action_cols, "action_", ""))



```
```{r DEMO}
# make age a factor because it will make using it as a variable easier
gvm_clean$age <- as.factor(gvm_clean$age)

# create new df for the data we want
age_by_action <- gvm_clean |>
  select(age, starts_with("action")) |> # grabbing the variables of interest
  pivot_longer(!age, names_to = "action", values_to = "count") |> # pivoting
  group_by(age, action) |> # grouping to make summarizing
  summarize(n = sum(count, na.rm = TRUE)) |> # getting the counts for each category
  mutate(action = str_replace_all(action, "action_", ""), # simple text cleaning
         action = str_replace_all(action, "_", " "),
         action = str_to_title(action))

age_by_action |>
  ggplot(aes(fct_reorder(action, desc(n)), n, fill = age)) + # grab variables and reorder action
  geom_col()  +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = .6)) +
  labs(
    x = "Action",
    y = "Number",
    fill = "Age group",
    title = "Actions taken by Age group"
  ) +
  scale_fill_viridis_d(direction = -1) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1))) # this line makes sure there is no gap between the bottom of the bars and the horizontal axis
```

```{r exporting clean data}
write_csv(gvm_clean, "GVM_data.csv")
```





